num = int(input())

if num == 1:
    print("yoink a")
    print("yoink b")
    print("*slaps a on top of b*")
    print("yeet b")
    print("go touch some grass")
if num == 2:
    print("yoink a")
    print("bruh b is lowkey just 0")
    print("rip this b fell off by a")
    print("vibe check a ratios b")
    print("simp for 7")
    print("bruh a is lowkey just b")
    print("yeet a")
    print("go touch some grass")
if num == 3:
    print("yoink n")
    print("yoink a")
    print("bruh m is lowkey just a[0]")
    print("bruh i is lowkey just 1")
    print("vibe check n ratios i")
    print("simp for 9")
    print("yeet m")
    print("go touch some grass")
    print("vibe check a[i] ratios m")
    print("bruh m is lowkey just a[i]")
    print("*slaps 1 on top of i*")
    print("simp for 5")
if num == 4:
    print("yoink n")
    print("yoink a")
    print("bruh i is lowkey just n")
    print("vibe check i ratios 1")
    print("simp for 7")
    print("simp for 22")
    print("bruh j is lowkey just 1")
    print("vibe check i ratios j")
    print("simp for 11")
    print("simp for 20")
    print("bruh k is lowkey just j")
    print("*slaps -1 on top of k*")
    print("vibe check a[k] ratios a[j]")
    print("simp for 18")
    print("bruh tmp is lowkey just a[j]")
    print("bruh a[j] is lowkey just a[k]")
    print("bruh a[k] is lowkey just tmp")
    print("*slaps 1 on top of j*")
    print("simp for 8")
    print("rip this i fell off by 1")
    print("simp for 4")
    print("yoink k")
    print("rip this k fell off by 1")
    print("yeet a[k]")
    print("go touch some grass")